### ISSUE TITLE
Authentication errors

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_forum#57]
It seems that it's no longer possible to authenticate on the forum.

* If I log in from the UI, I'm authenticated in the UI but not in Discourse.
* If I log in from Discourse, I am redirected to a blank page with error ``Votre compte est en attente d'approbation. Vous recevrez une notification par courriel lorsque vous êtes approuvé.``. If I then go to the UI, I am correctly authenticated, but still not in Discourse.

**Comment by asaunier** [comment]
@fbunoz has found the problem in the admin interface and fixed it.

**Comment by fbunoz** [comment]
The problem was caused by a change in an admin setting : 
> must approve users : 
Staff must approve all new user accounts before they are allowed to access the site. WARNING: enabling this for a live site will revoke access for existing non-staff users!

This setting has been actived this afternoon.
It is usefull for the final migration forum, but for the demo it is not necessary.
I desactived this setting.
